### ISSUE TITLE
Npm i fails if no .git due to githooks

### ISSUE THREAD

**Issue by latentflip** [HenrikJoreteg/humanjs#1]
This is a silly little thing, but might trip other people up on first look.

I just wanted to try it out, so I skipped the `git init` step, thinking I wasn't going to commit it anyway, but then npm i failed.

Could you just run git init as part of the setup script maybe?

**Comment by HenrikJoreteg** [comment]
i filed a bug on precommit-hook for this to have it warn instead of blow up. Also, removed it for now.
