### ISSUE TITLE
Missing dependency on Windows

### ISSUE THREAD

**Issue by zs-zs** [HenrikJoreteg/humanjs#11]
On Windows 8, with npm 1.3.11, there is a missing dependency which needs to be installed by hand to start the scaffolded applications without errors.
If you try to run a newly scaffolded application on Windows, unfortunately, you will get an error:

```
C:\HumanJS\asdf>node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'source-map'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\HumanJS\asdf\node_modules\moonboots\node_modules\browse
rify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map\index.
js:2:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

It turns out that the "source-map" dependency of the "inline-source-map" (which is a dependency of the combine-source-map which is a dependency of the browser-pack, etc.) doesn't get installed correctly when you install the dependencies with

```
npm i
```

from the root. 
However I don't know if this is a bug of the HumanJS scaffolding infrastructure or the npm itself.

A workaround which has worked for me: to navigate to the inline-source-map in the dependency chain, navigate to its `node_modules` folder, and then just say

```
npm i
```

This will install the missing dependency and the server script should start without any errors.

**Comment by HenrikJoreteg** [comment]
i've had reports that everything works on windows now. Could you try this again with humanjs 1.0.1 from npm?

**Comment by zs-zs** [comment]
Thanks, everything's works now! (Tested on Windows 8.1.)
